version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /volume1/docker/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8081:80
    volumes:
      - /volume1/docker/nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /volume1/docker/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
