version: "3.7"
services:
  controller:
    image: jacobalberty/unifi:latest
    init: true
    restart: always
    volumes:
      - /volume1/docker/unifi:/unifi
    environment:
      - TZ=Europe/Brussels
    ports:
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8880:8880/tcp"
      - "8843:8843/tcp"
      - "10001:10001/udp"
