version: '3.7'
services:
  controller:
    image: jacobalberty/unifi:latest
    init: true
    restart: always
    volumes:
      - /volume1/docker/unifi:/unifi
    environment:
      - TZ=Europe/Brussels
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
